// src/lib/components/CampaignCard.svelte
<script lang="ts">
	import type { campaigns } from '$lib/server/db/schema';

	type Campaign = typeof campaigns.$inferSelect;

	type Props = {
		campaign: Campaign;
		role: 'mj' | 'player';
	};

	let { campaign, role }: Props = $props();

	const formatDate = (date: Date) =>
		new Date(date).toLocaleDateString('fr-FR', {
			day: 'numeric',
			month: 'short',
			year: 'numeric'
		});
</script>

<a
	href="/campaign/{campaign.id}"
	class="card bg-base-100 shadow-md transition-shadow hover:shadow-xl"
>
	<div class="card-body">
		<h3 class="card-title">{campaign.name}</h3>
		<p class="text-sm text-base-content/60">{campaign.universe || 'Univers non défini'}</p>

		<p class="line-clamp-2 text-sm">{campaign.description || 'Aucune description'}</p>

		<div class="mt-4 card-actions items-center justify-between">
			<span class="badge {role === 'mj' ? 'badge-primary' : 'badge-secondary'}">
				{role === 'mj' ? 'Maître de Jeu' : 'Joueur'}
			</span>
			<span class="text-xs text-base-content/50">{formatDate(campaign.updatedAt)}</span>
		</div>
	</div>
</a>

// mockup/components/CampaignCard.tsx
import React from 'react';
import { Campaign } from '../types';
import { Users, Scroll } from 'lucide-react';

interface CampaignCardProps {
  campaign: Campaign;
  role: 'mj' | 'player';
  onClick: () => void;
}

export function CampaignCard({ campaign, role, onClick }: CampaignCardProps) {
  const sessionCount = campaign.sessions.length;

  return (
    <div
      onClick={onClick}
      className="bg-white rounded-lg shadow hover:shadow-lg transition-shadow duration-200 p-6 cursor-pointer"
    >
      <div className="mb-4">
        <h3 className="text-xl font-bold text-gray-900">{campaign.name}</h3>
        <p className="text-sm text-gray-500 mt-1">{campaign.universe}</p>
      </div>

      <p className="text-gray-700 text-sm mb-4 line-clamp-2">
        {campaign.description}
      </p>

      <div className="space-y-2 mb-4">
        <div className="flex items-center gap-2 text-sm text-gray-600">
          <Scroll className="w-4 h-4" />
          <span>{sessionCount} session{sessionCount !== 1 ? 's' : ''}</span>
        </div>
        <div className="flex items-center gap-2 text-sm text-gray-600">
          <Users className="w-4 h-4" />
          <span>
            {role === 'mj' ? `${campaign.players.length} joueur${campaign.players.length !== 1 ? 's' : ''}` : 'Joueur'}
          </span>
        </div>
      </div>

      <div className="flex items-center justify-between pt-4 border-t">
        <span className={`text-xs font-semibold px-3 py-1 rounded-full ${
          role === 'mj'
            ? 'bg-blue-100 text-blue-800'
            : 'bg-purple-100 text-purple-800'
        }`}>
          {role === 'mj' ? '🔐 Maître de Jeu' : '👁️ Joueur'}
        </span>
        <span className="text-xs text-gray-500">
          {new Date(campaign.updatedAt).toLocaleDateString('fr-FR')}
        </span>
      </div>
    </div>
  );
}
