// mockup/src/components/Header.tsx
import React from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { Dice6, LogOut } from 'lucide-react';

export function Header() {
  const { user, logout } = useAuth();
  const navigate = useNavigate();

  const handleLogout = () => {
    logout();
    navigate('/login');
  };

  return (
    <header className="bg-white shadow">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
        <div className="flex justify-between items-center">
          <div className="flex items-center gap-2">
            <Dice6 className="w-8 h-8 text-blue-600" />
            <h1 className="text-2xl font-bold text-gray-900">CampaignHub</h1>
          </div>
          <div className="flex items-center gap-4">
            <span className="text-gray-600">{user?.name}</span>
            <button
              onClick={handleLogout}
              className="flex items-center gap-2 text-gray-600 hover:text-gray-900"
            >
              <LogOut className="w-5 h-5" />
              Déconnexion
            </button>
          </div>
        </div>
      </div>
    </header>
  );
}

// src/lib/components/Header.svelte
<script lang="ts">
	import type { SessionUser } from '$lib/server/auth/session';

	type Props = {
		user: SessionUser;
	};

	let { user }: Props = $props();
</script>

<header class="navbar bg-base-100 shadow">
	<div class="mx-auto flex w-full max-w-7xl justify-between px-4">
		<a href="/dashboard" class="btn text-xl btn-ghost">CampaignHub</a>
		<div class="flex items-center gap-4">
			<span class="text-sm">{user.name}</span>
			<form action="/logout" method="POST">
				<button type="submit" class="btn btn-ghost btn-sm">Déconnexion</button>
			</form>
		</div>
	</div>
</header>
