// mockup/components/PlayerSpace.tsx
import React, { useState } from 'react';
import { Campaign } from '../types';
import { Eye } from 'lucide-react';

interface PlayerSpaceProps {
  campaign: Campaign;
}

export function PlayerSpace({ campaign }: PlayerSpaceProps) {
  const [selectedSession, setSelectedSession] = useState(campaign.sessions[0] || null);

  const publicSessions = campaign.sessions.filter(s => s.isPublished);

  return (
    <div className="space-y-6">
      <div className="bg-purple-50 border border-purple-200 rounded-lg p-6 flex items-center gap-4">
        <Eye className="w-8 h-8 text-purple-600" />
        <div>
          <h2 className="text-2xl font-bold text-purple-900">{campaign.name}</h2>
          <p className="text-purple-700">{campaign.universe} - Espace Joueur</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-1">
          <div className="bg-white rounded-lg shadow p-6">
            <h3 className="text-lg font-bold text-gray-900 mb-4">📖 Résumés de Sessions</h3>
            {publicSessions.length === 0 ? (
              <p className="text-gray-600">Aucun résumé disponible pour le moment</p>
            ) : (
              <div className="space-y-2">
                {publicSessions.map((session) => (
                  <button
                    key={session.id}
                    onClick={() => setSelectedSession(session)}
                    className={`w-full text-left p-3 rounded-lg transition duration-200 ${
                      selectedSession?.id === session.id
                        ? 'bg-blue-100 text-blue-900 border border-blue-300'
                        : 'hover:bg-gray-100 text-gray-900'
                    }`}
                  >
                    <div className="font-semibold">Session {session.number}</div>
                    <div className="text-xs text-gray-600">
                      {new Date(session.sessionDate).toLocaleDateString('fr-FR')}
                    </div>
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>

        <div className="lg:col-span-2">
          {selectedSession ? (
            <div className="bg-white rounded-lg shadow p-6 space-y-6">
              <div>
                <h3 className="text-2xl font-bold text-gray-900 mb-2">
                  Session {selectedSession.number}
                </h3>
                <p className="text-gray-600">
                  {new Date(selectedSession.sessionDate).toLocaleDateString('fr-FR', {
                    weekday: 'long',
                    year: 'numeric',
                    month: 'long',
                    day: 'numeric',
                  })}
                </p>
              </div>

              <div className="border-t pt-4">
                <h4 className="text-lg font-semibold text-gray-900 mb-2">📝 Résumé</h4>
                <div className="prose prose-sm max-w-none">
                  <p className="text-gray-700 whitespace-pre-wrap">
                    {selectedSession.summary}
                  </p>
                </div>
              </div>

              {selectedSession.publicNotes && (
                <div className="border-t pt-4">
                  <h4 className="text-lg font-semibold text-gray-900 mb-2">✏️ Notes publiques</h4>
                  <p className="text-gray-700 whitespace-pre-wrap">
                    {selectedSession.publicNotes}
                  </p>
                </div>
              )}

              {selectedSession.nextSessionTheme && (
                <div className="border-t pt-4 bg-blue-50 p-4 rounded-lg">
                  <h4 className="text-lg font-semibold text-blue-900 mb-2">🎲 Prochaine session</h4>
                  <p className="text-blue-800">{selectedSession.nextSessionTheme}</p>
                  {selectedSession.nextSessionDate && (
                    <p className="text-sm text-blue-700 mt-2">
                      Prévue le {new Date(selectedSession.nextSessionDate).toLocaleDateString('fr-FR')}
                    </p>
                  )}
                </div>
              )}
            </div>
          ) : (
            <div className="bg-white rounded-lg shadow p-12 text-center">
              <p className="text-gray-600">Sélectionnez une session pour voir les détails</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// src/lib/components/PlayerSpace.svelte
<script lang="ts">
	interface Campaign {
		id: string;
		name: string;
		description: string;
		universe: string;
		masterId: string;
	}

	interface Session {
		id: string;
		number: number;
		sessionDate: Date;
		summary: string;
		publicNotes: string;
		isPublished: boolean;
		nextSessionDate: Date | null;
		nextSessionTheme: string;
	}

	let { campaign, sessions }: { campaign: Campaign; sessions: Session[] } = $props();

	// Players only see published sessions
	let publicSessions = $derived(sessions.filter((s) => s.isPublished));
	let selectedSessionId = $state<string | null>(null);

	// Auto-select first public session
	$effect(() => {
		if (publicSessions.length > 0 && !selectedSessionId) {
			selectedSessionId = publicSessions[0].id;
		}
	});

	let selectedSession = $derived(publicSessions.find((s) => s.id === selectedSessionId) ?? null);

	function formatDate(date: Date): string {
		return new Date(date).toLocaleDateString('fr-FR', {
			weekday: 'long',
			year: 'numeric',
			month: 'long',
			day: 'numeric'
		});
	}

	function formatShortDate(date: Date): string {
		return new Date(date).toLocaleDateString('fr-FR');
	}
</script>

<div class="space-y-6">
	<!-- Header -->
	<div class="flex items-center gap-4 rounded-lg border border-secondary/30 bg-secondary/10 p-6">
		<svg
			xmlns="http://www.w3.org/2000/svg"
			class="h-8 w-8 text-secondary"
			fill="none"
			viewBox="0 0 24 24"
			stroke="currentColor"
		>
			<path
				stroke-linecap="round"
				stroke-linejoin="round"
				stroke-width="2"
				d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"
			/>
			<path
				stroke-linecap="round"
				stroke-linejoin="round"
				stroke-width="2"
				d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"
			/>
		</svg>
		<div>
			<h2 class="text-2xl font-bold text-secondary">{campaign.name}</h2>
			<p class="text-secondary/80">{campaign.universe || 'Univers non défini'} - Espace Joueur</p>
		</div>
	</div>

	<!-- Sessions Grid -->
	<div class="grid grid-cols-1 gap-6 lg:grid-cols-3">
		<!-- Session List -->
		<div class="lg:col-span-1">
			<div class="card bg-base-100 shadow">
				<div class="card-body">
					<h3 class="card-title text-lg">📖 Résumés de Sessions</h3>
					{#if publicSessions.length === 0}
						<p class="text-base-content/60">Aucun résumé disponible pour le moment</p>
					{:else}
						<div class="space-y-2">
							{#each publicSessions as session (session.id)}
								<button
									class="btn w-full justify-start text-left btn-ghost"
									class:btn-active={selectedSessionId === session.id}
									onclick={() => (selectedSessionId = session.id)}
								>
									<div>
										<div class="font-semibold">Session {session.number}</div>
										<div class="text-xs opacity-60">
											{formatShortDate(session.sessionDate)}
										</div>
									</div>
								</button>
							{/each}
						</div>
					{/if}
				</div>
			</div>
		</div>

		<!-- Session Detail -->
		<div class="lg:col-span-2">
			{#if selectedSession}
				<div class="card bg-base-100 shadow">
					<div class="card-body space-y-6">
						<!-- Header -->
						<div>
							<h3 class="text-2xl font-bold">Session {selectedSession.number}</h3>
							<p class="text-base-content/60">{formatDate(selectedSession.sessionDate)}</p>
						</div>

						<!-- Summary -->
						<div class="border-t pt-4">
							<h4 class="mb-2 text-lg font-semibold">📝 Résumé</h4>
							<p class="whitespace-pre-wrap">
								{selectedSession.summary || 'Aucun résumé'}
							</p>
						</div>

						<!-- Public Notes -->
						{#if selectedSession.publicNotes}
							<div class="border-t pt-4">
								<h4 class="mb-2 text-lg font-semibold">✏️ Notes publiques</h4>
								<p class="whitespace-pre-wrap">
									{selectedSession.publicNotes}
								</p>
							</div>
						{/if}

						<!-- Next Session -->
						{#if selectedSession.nextSessionTheme}
							<div class="rounded-lg border border-info/30 bg-info/10 p-4">
								<h4 class="mb-2 text-lg font-semibold text-info">🎲 Prochaine session</h4>
								<p class="text-info/90">{selectedSession.nextSessionTheme}</p>
								{#if selectedSession.nextSessionDate}
									<p class="mt-2 text-sm text-info/70">
										Prévue le {formatShortDate(selectedSession.nextSessionDate)}
									</p>
								{/if}
							</div>
						{/if}
					</div>
				</div>
			{:else}
				<div class="card bg-base-100 shadow">
					<div class="card-body py-12 text-center">
						<p class="text-base-content/60">Sélectionnez une session pour voir les détails</p>
					</div>
				</div>
			{/if}
		</div>
	</div>
</div>
